apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: 5stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 5stack-timescaledb
                    operator: In
                    values:
                      - 'true'
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg17
          args:
            - postgres
            - '-c'
            - fivestack.app_key=$(APP_KEY)
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: timescaledb-secrets
            - configMapRef:
                name: timescaledb-config
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: APP_KEY
          volumeMounts:
            - name: api-secrets
              mountPath: /etc/api-secrets
              readOnly: true
            - name: timescaledb-data
              mountPath: /var/lib/postgresql/data
              subPath: timescaledb
      volumes:
        - name: api-secrets
          secret:
            secretName: api-secrets
        - name: timescaledb-data
          persistentVolumeClaim:
            claimName: timescaledb-pvc