apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:

  namespace: 5stack
spec:
  ingressClassName: nginx
  rules:
    - host: $(API_DOMAIN)
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /me
            pathType: Exact
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /matches
            pathType: Prefix
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /server
            pathType: Prefix
          - backend:
              service:
                name: hasura
                port:
                  number: 8080
            path: /v1
            pathType: Prefix
          - backend:
              service:
                name: hasura
                port:
                  number: 8080
            path: /v1alpha1
            pathType: Prefix
          - backend:
              service:
                name: hasura
                port:
                  number: 8080
            path: /v2
            pathType: Prefix
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /game-server-node/script
            pathType: Prefix
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /game-server-node/ping
            pathType: Prefix
    - host: $(WEB_DOMAIN)
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /auth
            pathType: Prefix
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /quick-connect
            pathType: Exact
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /discord-bot
            pathType: Exact
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /matches/[^/]+/backup-rounds/map/.*
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/chunked-transfer-encoding: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  namespace: 5stack
spec:
  ingressClassName: nginx
  rules:
    - host: upload.5stack.gg
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 5585
            path: /demos
            pathType: Prefix