apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-game-server-node-connector
  name: dev-game-server-node-connector
  namespace: 5stack
spec:
  selector:
    matchLabels:
      app: dev-game-server-node-connector
  template:
    metadata:
      labels:
        app: dev-game-server-node-connector
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: 5stack-dev-server
                operator: In
                values:
                  - "true"
      serviceAccountName: game-server-node-connector
      containers:
        - image: ghcr.io/5stackgg/game-server-node:latest
          name: dev-game-server-node-connector
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: server-files
              mountPath: /serverfiles
      volumes:
        - name: server-files
          hostPath:
            path: /opt/5stack/serverfiles
            type: Directory
   
