apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: 5stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 5stack-web
                    operator: In
                    values:
                      - 'true'
      containers:
        - image: ghcr.io/5stackgg/web:latest
          name: web
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_PUBLIC_API_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: API_DOMAIN
            - name: NUXT_PUBLIC_WEB_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: WEB_DOMAIN
            - name: NUXT_PUBLIC_WS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: WS_DOMAIN
            - name: NUXT_PUBLIC_TYPESENSE_HOST
              valueFrom:
                configMapKeyRef:
                  name: typesense-config
                  key: TYPESENSE_HOST 
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-secrets
                  key: TYPESENSE_API_KEY
